---
:consumer_key: PGqBBjNCsk3YDQsfKNTer6wV1
:consumer_secret: RYgXrdXEWRLFFl0JNcgiIdIxdXaihnQXt9XBBeZiVUt9A9shZj
:access_token: 3310925289-nqnBg5lyNYpdW3ZiTVtvcea07W5JjPJozKSr7Rd
:access_token_secret: SYQzuuoDocJjs1zUsKrvbzyTc7oQzV6hRiN3oF4W7ZY1f
